name: co building
on: 
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: |
          ls ${{ github.workspace }}
          go build co.go
          go test -v
